name: AWS Lambda Deploy

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Set environment variable
        run: |
          cp .env.example .env

          sed -i "s|^SECRET_KEY=\$|SECRET_KEY=${{ secrets.SECRET_KEY }}|" .env

          sed -i "s|^POSTGRES_HOST=\$|POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}|" .env
          sed -i "s|^POSTGRES_PORT=\$|POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}|" .env
          sed -i "s|^POSTGRES_DB=\$|POSTGRES_DB=${{ secrets.POSTGRES_DB }}|" .env
          sed -i "s|^POSTGRES_USER=\$|POSTGRES_USER=${{ secrets.POSTGRES_USER }}|" .env
          sed -i "s|^POSTGRES_PASSWORD=\$|POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}|" .env

          sed -i "s|^AWS_ACCESS_KEY_ID=\$|AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}|" .env
          sed -i "s|^AWS_SECRET_ACCESS_KEY=\$|AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}|" .env

          sed -i "s|^POSTMARK_TOKEN=\$|POSTMARK_TOKEN=${{ secrets.POSTMARK_TOKEN }}|" .env

      - name: Deploying a zip archive
        run: |
          uv export --frozen --no-dev --no-editable -o requirements.txt
          uv pip install --no-installer-metadata --no-compile-bytecode --python-platform x86_64-manylinux2014 --target packages -r requirements.txt

      - name: Application Packaging
        run: |
          cd packages
          zip -r ../package.zip .
          cd ..
          zip -r package.zip app lambda_function.py .env 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: To Lambda
        run: aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} --zip-file fileb://package.zip
